#!/bin/bash
out='output'
plants='plants.txt'
logfile='timelog'
main='gafarm'
threads=2
#delete old executable
rm $main $out
#compile program
g++ -fopenmp -o $main main.cpp plant.cpp ga.cpp 
#execute program, pipe output
./$main $threads $plants $logfile > $out 
more output
